// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/SergeyRG/secrets-manager/client/internal/app/registre/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRegistreProvider is a mock of RegistreProvider interface.
type MockRegistreProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRegistreProviderMockRecorder
	isgomock struct{}
}

// MockRegistreProviderMockRecorder is the mock recorder for MockRegistreProvider.
type MockRegistreProviderMockRecorder struct {
	mock *MockRegistreProvider
}

// NewMockRegistreProvider creates a new mock instance.
func NewMockRegistreProvider(ctrl *gomock.Controller) *MockRegistreProvider {
	mock := &MockRegistreProvider{ctrl: ctrl}
	mock.recorder = &MockRegistreProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistreProvider) EXPECT() *MockRegistreProviderMockRecorder {
	return m.recorder
}

// Registre mocks base method.
func (m *MockRegistreProvider) Registre(arg0 context.Context, arg1 domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Registre", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Registre indicates an expected call of Registre.
func (mr *MockRegistreProviderMockRecorder) Registre(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Registre", reflect.TypeOf((*MockRegistreProvider)(nil).Registre), arg0, arg1)
}

// MockUserDataProvider is a mock of UserDataProvider interface.
type MockUserDataProvider struct {
	ctrl     *gomock.Controller
	recorder *MockUserDataProviderMockRecorder
	isgomock struct{}
}

// MockUserDataProviderMockRecorder is the mock recorder for MockUserDataProvider.
type MockUserDataProviderMockRecorder struct {
	mock *MockUserDataProvider
}

// NewMockUserDataProvider creates a new mock instance.
func NewMockUserDataProvider(ctrl *gomock.Controller) *MockUserDataProvider {
	mock := &MockUserDataProvider{ctrl: ctrl}
	mock.recorder = &MockUserDataProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserDataProvider) EXPECT() *MockUserDataProviderMockRecorder {
	return m.recorder
}

// GetUserData mocks base method.
func (m *MockUserDataProvider) GetUserData(arg0 context.Context) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserData", arg0)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserData indicates an expected call of GetUserData.
func (mr *MockUserDataProviderMockRecorder) GetUserData(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserData", reflect.TypeOf((*MockUserDataProvider)(nil).GetUserData), arg0)
}
