// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEncryptedKeyRepository is a mock of EncryptedKeyRepository interface.
type MockEncryptedKeyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEncryptedKeyRepositoryMockRecorder
	isgomock struct{}
}

// MockEncryptedKeyRepositoryMockRecorder is the mock recorder for MockEncryptedKeyRepository.
type MockEncryptedKeyRepositoryMockRecorder struct {
	mock *MockEncryptedKeyRepository
}

// NewMockEncryptedKeyRepository creates a new mock instance.
func NewMockEncryptedKeyRepository(ctrl *gomock.Controller) *MockEncryptedKeyRepository {
	mock := &MockEncryptedKeyRepository{ctrl: ctrl}
	mock.recorder = &MockEncryptedKeyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncryptedKeyRepository) EXPECT() *MockEncryptedKeyRepositoryMockRecorder {
	return m.recorder
}

// GetEncryptedKey mocks base method.
func (m *MockEncryptedKeyRepository) GetEncryptedKey(ctx context.Context) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEncryptedKey", ctx)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEncryptedKey indicates an expected call of GetEncryptedKey.
func (mr *MockEncryptedKeyRepositoryMockRecorder) GetEncryptedKey(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEncryptedKey", reflect.TypeOf((*MockEncryptedKeyRepository)(nil).GetEncryptedKey), ctx)
}

// SaveEncryptedKey mocks base method.
func (m *MockEncryptedKeyRepository) SaveEncryptedKey(ctx context.Context, encKey []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEncryptedKey", ctx, encKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEncryptedKey indicates an expected call of SaveEncryptedKey.
func (mr *MockEncryptedKeyRepositoryMockRecorder) SaveEncryptedKey(ctx, encKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEncryptedKey", reflect.TypeOf((*MockEncryptedKeyRepository)(nil).SaveEncryptedKey), ctx, encKey)
}
