// Code generated by MockGen. DO NOT EDIT.
// Source: password_provider.go
//
// Generated by this command:
//
//	mockgen -source=password_provider.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPasswdProvider is a mock of PasswdProvider interface.
type MockPasswdProvider struct {
	ctrl     *gomock.Controller
	recorder *MockPasswdProviderMockRecorder
	isgomock struct{}
}

// MockPasswdProviderMockRecorder is the mock recorder for MockPasswdProvider.
type MockPasswdProviderMockRecorder struct {
	mock *MockPasswdProvider
}

// NewMockPasswdProvider creates a new mock instance.
func NewMockPasswdProvider(ctrl *gomock.Controller) *MockPasswdProvider {
	mock := &MockPasswdProvider{ctrl: ctrl}
	mock.recorder = &MockPasswdProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswdProvider) EXPECT() *MockPasswdProviderMockRecorder {
	return m.recorder
}

// CreatePassword mocks base method.
func (m *MockPasswdProvider) CreatePassword(arg0 context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePassword", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePassword indicates an expected call of CreatePassword.
func (mr *MockPasswdProviderMockRecorder) CreatePassword(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePassword", reflect.TypeOf((*MockPasswdProvider)(nil).CreatePassword), arg0)
}

// GetPassword mocks base method.
func (m *MockPasswdProvider) GetPassword(arg0 context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPassword", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPassword indicates an expected call of GetPassword.
func (mr *MockPasswdProviderMockRecorder) GetPassword(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPassword", reflect.TypeOf((*MockPasswdProvider)(nil).GetPassword), arg0)
}
