// Code generated by MockGen. DO NOT EDIT.
// Source: password_creds_provider.go
//
// Generated by this command:
//
//	mockgen -source=password_creds_provider.go -destination=mocks/mocks.go -package=mockspackage usecases
//

// Package mockspackage is a generated GoMock package.
package mockspackage

import (
	context "context"
	reflect "reflect"

	authclient "github.com/SergeyRG/secrets-manager/client/internal/app/auth/infra/resty_passwd_auth_client"
	gomock "go.uber.org/mock/gomock"
)

// MockPasswdCredsProvider is a mock of PasswdCredsProvider interface.
type MockPasswdCredsProvider struct {
	ctrl     *gomock.Controller
	recorder *MockPasswdCredsProviderMockRecorder
	isgomock struct{}
}

// MockPasswdCredsProviderMockRecorder is the mock recorder for MockPasswdCredsProvider.
type MockPasswdCredsProviderMockRecorder struct {
	mock *MockPasswdCredsProvider
}

// NewMockPasswdCredsProvider creates a new mock instance.
func NewMockPasswdCredsProvider(ctrl *gomock.Controller) *MockPasswdCredsProvider {
	mock := &MockPasswdCredsProvider{ctrl: ctrl}
	mock.recorder = &MockPasswdCredsProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswdCredsProvider) EXPECT() *MockPasswdCredsProviderMockRecorder {
	return m.recorder
}

// GetCreds mocks base method.
func (m *MockPasswdCredsProvider) GetCreds(arg0 context.Context) (authclient.PasswdCreds, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCreds", arg0)
	ret0, _ := ret[0].(authclient.PasswdCreds)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCreds indicates an expected call of GetCreds.
func (mr *MockPasswdCredsProviderMockRecorder) GetCreds(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCreds", reflect.TypeOf((*MockPasswdCredsProvider)(nil).GetCreds), arg0)
}
