// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mocks.go -package=mockspackage usecases
//

// Package mockspackage is a generated GoMock package.
package mockspackage

import (
	context "context"
	io "io"
	reflect "reflect"

	domain "github.com/SergeyRG/secrets-manager/client/internal/app/secrets/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSecretMetadataRepository is a mock of SecretMetadataRepository interface.
type MockSecretMetadataRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSecretMetadataRepositoryMockRecorder
	isgomock struct{}
}

// MockSecretMetadataRepositoryMockRecorder is the mock recorder for MockSecretMetadataRepository.
type MockSecretMetadataRepositoryMockRecorder struct {
	mock *MockSecretMetadataRepository
}

// NewMockSecretMetadataRepository creates a new mock instance.
func NewMockSecretMetadataRepository(ctrl *gomock.Controller) *MockSecretMetadataRepository {
	mock := &MockSecretMetadataRepository{ctrl: ctrl}
	mock.recorder = &MockSecretMetadataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretMetadataRepository) EXPECT() *MockSecretMetadataRepositoryMockRecorder {
	return m.recorder
}

// AddSecretMetadata mocks base method.
func (m *MockSecretMetadataRepository) AddSecretMetadata(arg0 context.Context, arg1 domain.SecretsMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSecretMetadata", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSecretMetadata indicates an expected call of AddSecretMetadata.
func (mr *MockSecretMetadataRepositoryMockRecorder) AddSecretMetadata(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSecretMetadata", reflect.TypeOf((*MockSecretMetadataRepository)(nil).AddSecretMetadata), arg0, arg1)
}

// GetUserSecretMetadataByName mocks base method.
func (m *MockSecretMetadataRepository) GetUserSecretMetadataByName(ctx context.Context, sName string, version int) (domain.SecretsMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSecretMetadataByName", ctx, sName, version)
	ret0, _ := ret[0].(domain.SecretsMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSecretMetadataByName indicates an expected call of GetUserSecretMetadataByName.
func (mr *MockSecretMetadataRepositoryMockRecorder) GetUserSecretMetadataByName(ctx, sName, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSecretMetadataByName", reflect.TypeOf((*MockSecretMetadataRepository)(nil).GetUserSecretMetadataByName), ctx, sName, version)
}

// GetUserSecretsMetadataPage mocks base method.
func (m *MockSecretMetadataRepository) GetUserSecretsMetadataPage(ctx context.Context, page, perPage int) ([]domain.SecretsMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSecretsMetadataPage", ctx, page, perPage)
	ret0, _ := ret[0].([]domain.SecretsMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSecretsMetadataPage indicates an expected call of GetUserSecretsMetadataPage.
func (mr *MockSecretMetadataRepositoryMockRecorder) GetUserSecretsMetadataPage(ctx, page, perPage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSecretsMetadataPage", reflect.TypeOf((*MockSecretMetadataRepository)(nil).GetUserSecretsMetadataPage), ctx, page, perPage)
}

// MockSecretDataRepository is a mock of SecretDataRepository interface.
type MockSecretDataRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSecretDataRepositoryMockRecorder
	isgomock struct{}
}

// MockSecretDataRepositoryMockRecorder is the mock recorder for MockSecretDataRepository.
type MockSecretDataRepositoryMockRecorder struct {
	mock *MockSecretDataRepository
}

// NewMockSecretDataRepository creates a new mock instance.
func NewMockSecretDataRepository(ctrl *gomock.Controller) *MockSecretDataRepository {
	mock := &MockSecretDataRepository{ctrl: ctrl}
	mock.recorder = &MockSecretDataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretDataRepository) EXPECT() *MockSecretDataRepositoryMockRecorder {
	return m.recorder
}

// AddSecretData mocks base method.
func (m *MockSecretDataRepository) AddSecretData(ctx context.Context, smt domain.SecretsMetadata, data io.ReadCloser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSecretData", ctx, smt, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSecretData indicates an expected call of AddSecretData.
func (mr *MockSecretDataRepositoryMockRecorder) AddSecretData(ctx, smt, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSecretData", reflect.TypeOf((*MockSecretDataRepository)(nil).AddSecretData), ctx, smt, data)
}

// GetSecretData mocks base method.
func (m *MockSecretDataRepository) GetSecretData(ctx context.Context, smt domain.SecretsMetadata) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretData", ctx, smt)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretData indicates an expected call of GetSecretData.
func (mr *MockSecretDataRepositoryMockRecorder) GetSecretData(ctx, smt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretData", reflect.TypeOf((*MockSecretDataRepository)(nil).GetSecretData), ctx, smt)
}
