// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	io "io"
	reflect "reflect"

	domain "github.com/SergeyRG/secrets-manager/client/internal/app/secrets/domain"
	cli "github.com/SergeyRG/secrets-manager/client/internal/app/shared/infra/cli"
	gomock "go.uber.org/mock/gomock"
)

// MockView is a mock of View interface.
type MockView struct {
	ctrl     *gomock.Controller
	recorder *MockViewMockRecorder
	isgomock struct{}
}

// MockViewMockRecorder is the mock recorder for MockView.
type MockViewMockRecorder struct {
	mock *MockView
}

// NewMockView creates a new mock instance.
func NewMockView(ctrl *gomock.Controller) *MockView {
	mock := &MockView{ctrl: ctrl}
	mock.recorder = &MockViewMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockView) EXPECT() *MockViewMockRecorder {
	return m.recorder
}

// ProvideDataToUser mocks base method.
func (m *MockView) ProvideDataToUser(arg0 domain.SecretsMetadata, arg1 io.ReadCloser, arg2 cli.Prompter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProvideDataToUser", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProvideDataToUser indicates an expected call of ProvideDataToUser.
func (mr *MockViewMockRecorder) ProvideDataToUser(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProvideDataToUser", reflect.TypeOf((*MockView)(nil).ProvideDataToUser), arg0, arg1, arg2)
}

// MockSecretDataGetter is a mock of SecretDataGetter interface.
type MockSecretDataGetter struct {
	ctrl     *gomock.Controller
	recorder *MockSecretDataGetterMockRecorder
	isgomock struct{}
}

// MockSecretDataGetterMockRecorder is the mock recorder for MockSecretDataGetter.
type MockSecretDataGetterMockRecorder struct {
	mock *MockSecretDataGetter
}

// NewMockSecretDataGetter creates a new mock instance.
func NewMockSecretDataGetter(ctrl *gomock.Controller) *MockSecretDataGetter {
	mock := &MockSecretDataGetter{ctrl: ctrl}
	mock.recorder = &MockSecretDataGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretDataGetter) EXPECT() *MockSecretDataGetterMockRecorder {
	return m.recorder
}

// GetDataFromUser mocks base method.
func (m *MockSecretDataGetter) GetDataFromUser(arg0 cli.Prompter) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataFromUser", arg0)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataFromUser indicates an expected call of GetDataFromUser.
func (mr *MockSecretDataGetterMockRecorder) GetDataFromUser(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataFromUser", reflect.TypeOf((*MockSecretDataGetter)(nil).GetDataFromUser), arg0)
}
