// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SergeyRG/secrets-manager/server/internal/secrets/use-cases (interfaces: SecretMetadataRepository,SecretTextDataRepository,SecretBlobRepository,SecretDataSaver,SecretDataReceiver)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mocks.go -package=mocks github.com/SergeyRG/secrets-manager/server/internal/secrets/use-cases SecretMetadataRepository,SecretTextDataRepository,SecretBlobRepository,SecretDataSaver,SecretDataReceiver
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	iter "iter"
	reflect "reflect"

	domain "github.com/SergeyRG/secrets-manager/internal/shared/domain"
	domain0 "github.com/SergeyRG/secrets-manager/server/internal/secrets/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSecretMetadataRepository is a mock of SecretMetadataRepository interface.
type MockSecretMetadataRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSecretMetadataRepositoryMockRecorder
	isgomock struct{}
}

// MockSecretMetadataRepositoryMockRecorder is the mock recorder for MockSecretMetadataRepository.
type MockSecretMetadataRepositoryMockRecorder struct {
	mock *MockSecretMetadataRepository
}

// NewMockSecretMetadataRepository creates a new mock instance.
func NewMockSecretMetadataRepository(ctrl *gomock.Controller) *MockSecretMetadataRepository {
	mock := &MockSecretMetadataRepository{ctrl: ctrl}
	mock.recorder = &MockSecretMetadataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretMetadataRepository) EXPECT() *MockSecretMetadataRepositoryMockRecorder {
	return m.recorder
}

// AddSecretMetadata mocks base method.
func (m *MockSecretMetadataRepository) AddSecretMetadata(arg0 context.Context, arg1 domain0.SecretsMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSecretMetadata", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSecretMetadata indicates an expected call of AddSecretMetadata.
func (mr *MockSecretMetadataRepositoryMockRecorder) AddSecretMetadata(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSecretMetadata", reflect.TypeOf((*MockSecretMetadataRepository)(nil).AddSecretMetadata), arg0, arg1)
}

// GetUserSecretMetadataByName mocks base method.
func (m *MockSecretMetadataRepository) GetUserSecretMetadataByName(ctx context.Context, uId domain.UserID, sName string, version int) (domain0.SecretsMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSecretMetadataByName", ctx, uId, sName, version)
	ret0, _ := ret[0].(domain0.SecretsMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSecretMetadataByName indicates an expected call of GetUserSecretMetadataByName.
func (mr *MockSecretMetadataRepositoryMockRecorder) GetUserSecretMetadataByName(ctx, uId, sName, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSecretMetadataByName", reflect.TypeOf((*MockSecretMetadataRepository)(nil).GetUserSecretMetadataByName), ctx, uId, sName, version)
}

// GetUserSecretsMetadataPage mocks base method.
func (m *MockSecretMetadataRepository) GetUserSecretsMetadataPage(ctx context.Context, uID domain.UserID, page, perPage int) iter.Seq2[domain0.SecretsMetadata, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSecretsMetadataPage", ctx, uID, page, perPage)
	ret0, _ := ret[0].(iter.Seq2[domain0.SecretsMetadata, error])
	return ret0
}

// GetUserSecretsMetadataPage indicates an expected call of GetUserSecretsMetadataPage.
func (mr *MockSecretMetadataRepositoryMockRecorder) GetUserSecretsMetadataPage(ctx, uID, page, perPage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSecretsMetadataPage", reflect.TypeOf((*MockSecretMetadataRepository)(nil).GetUserSecretsMetadataPage), ctx, uID, page, perPage)
}

// MockSecretTextDataRepository is a mock of SecretTextDataRepository interface.
type MockSecretTextDataRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSecretTextDataRepositoryMockRecorder
	isgomock struct{}
}

// MockSecretTextDataRepositoryMockRecorder is the mock recorder for MockSecretTextDataRepository.
type MockSecretTextDataRepositoryMockRecorder struct {
	mock *MockSecretTextDataRepository
}

// NewMockSecretTextDataRepository creates a new mock instance.
func NewMockSecretTextDataRepository(ctrl *gomock.Controller) *MockSecretTextDataRepository {
	mock := &MockSecretTextDataRepository{ctrl: ctrl}
	mock.recorder = &MockSecretTextDataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretTextDataRepository) EXPECT() *MockSecretTextDataRepositoryMockRecorder {
	return m.recorder
}

// AddSecretData mocks base method.
func (m *MockSecretTextDataRepository) AddSecretData(ctx context.Context, smt domain0.SecretsMetadata, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSecretData", ctx, smt, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSecretData indicates an expected call of AddSecretData.
func (mr *MockSecretTextDataRepositoryMockRecorder) AddSecretData(ctx, smt, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSecretData", reflect.TypeOf((*MockSecretTextDataRepository)(nil).AddSecretData), ctx, smt, data)
}

// GetSecretData mocks base method.
func (m *MockSecretTextDataRepository) GetSecretData(ctx context.Context, smt domain0.SecretsMetadata) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretData", ctx, smt)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretData indicates an expected call of GetSecretData.
func (mr *MockSecretTextDataRepositoryMockRecorder) GetSecretData(ctx, smt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretData", reflect.TypeOf((*MockSecretTextDataRepository)(nil).GetSecretData), ctx, smt)
}

// MockSecretBlobRepository is a mock of SecretBlobRepository interface.
type MockSecretBlobRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSecretBlobRepositoryMockRecorder
	isgomock struct{}
}

// MockSecretBlobRepositoryMockRecorder is the mock recorder for MockSecretBlobRepository.
type MockSecretBlobRepositoryMockRecorder struct {
	mock *MockSecretBlobRepository
}

// NewMockSecretBlobRepository creates a new mock instance.
func NewMockSecretBlobRepository(ctrl *gomock.Controller) *MockSecretBlobRepository {
	mock := &MockSecretBlobRepository{ctrl: ctrl}
	mock.recorder = &MockSecretBlobRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretBlobRepository) EXPECT() *MockSecretBlobRepositoryMockRecorder {
	return m.recorder
}

// AddSecretData mocks base method.
func (m *MockSecretBlobRepository) AddSecretData(ctx context.Context, smt domain0.SecretsMetadata, data io.ReadCloser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSecretData", ctx, smt, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSecretData indicates an expected call of AddSecretData.
func (mr *MockSecretBlobRepositoryMockRecorder) AddSecretData(ctx, smt, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSecretData", reflect.TypeOf((*MockSecretBlobRepository)(nil).AddSecretData), ctx, smt, data)
}

// GetSecretData mocks base method.
func (m *MockSecretBlobRepository) GetSecretData(ctx context.Context, smt domain0.SecretsMetadata) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretData", ctx, smt)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretData indicates an expected call of GetSecretData.
func (mr *MockSecretBlobRepositoryMockRecorder) GetSecretData(ctx, smt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretData", reflect.TypeOf((*MockSecretBlobRepository)(nil).GetSecretData), ctx, smt)
}

// MockSecretDataSaver is a mock of SecretDataSaver interface.
type MockSecretDataSaver struct {
	ctrl     *gomock.Controller
	recorder *MockSecretDataSaverMockRecorder
	isgomock struct{}
}

// MockSecretDataSaverMockRecorder is the mock recorder for MockSecretDataSaver.
type MockSecretDataSaverMockRecorder struct {
	mock *MockSecretDataSaver
}

// NewMockSecretDataSaver creates a new mock instance.
func NewMockSecretDataSaver(ctrl *gomock.Controller) *MockSecretDataSaver {
	mock := &MockSecretDataSaver{ctrl: ctrl}
	mock.recorder = &MockSecretDataSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretDataSaver) EXPECT() *MockSecretDataSaverMockRecorder {
	return m.recorder
}

// SaveSecretData mocks base method.
func (m *MockSecretDataSaver) SaveSecretData(ctx context.Context, smd domain0.SecretsMetadata, data io.ReadCloser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSecretData", ctx, smd, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSecretData indicates an expected call of SaveSecretData.
func (mr *MockSecretDataSaverMockRecorder) SaveSecretData(ctx, smd, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSecretData", reflect.TypeOf((*MockSecretDataSaver)(nil).SaveSecretData), ctx, smd, data)
}

// MockSecretDataReceiver is a mock of SecretDataReceiver interface.
type MockSecretDataReceiver struct {
	ctrl     *gomock.Controller
	recorder *MockSecretDataReceiverMockRecorder
	isgomock struct{}
}

// MockSecretDataReceiverMockRecorder is the mock recorder for MockSecretDataReceiver.
type MockSecretDataReceiverMockRecorder struct {
	mock *MockSecretDataReceiver
}

// NewMockSecretDataReceiver creates a new mock instance.
func NewMockSecretDataReceiver(ctrl *gomock.Controller) *MockSecretDataReceiver {
	mock := &MockSecretDataReceiver{ctrl: ctrl}
	mock.recorder = &MockSecretDataReceiverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretDataReceiver) EXPECT() *MockSecretDataReceiverMockRecorder {
	return m.recorder
}

// ReceiveSecretData mocks base method.
func (m *MockSecretDataReceiver) ReceiveSecretData(ctx context.Context, smd domain0.SecretsMetadata) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveSecretData", ctx, smd)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReceiveSecretData indicates an expected call of ReceiveSecretData.
func (mr *MockSecretDataReceiverMockRecorder) ReceiveSecretData(ctx, smd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveSecretData", reflect.TypeOf((*MockSecretDataReceiver)(nil).ReceiveSecretData), ctx, smd)
}
