// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/SergeyRG/secrets-manager/internal/shared/domain"
	domain0 "github.com/SergeyRG/secrets-manager/server/internal/security/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockEncryptedKeyRepo is a mock of EncryptedKeyRepo interface.
type MockEncryptedKeyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockEncryptedKeyRepoMockRecorder
	isgomock struct{}
}

// MockEncryptedKeyRepoMockRecorder is the mock recorder for MockEncryptedKeyRepo.
type MockEncryptedKeyRepoMockRecorder struct {
	mock *MockEncryptedKeyRepo
}

// NewMockEncryptedKeyRepo creates a new mock instance.
func NewMockEncryptedKeyRepo(ctrl *gomock.Controller) *MockEncryptedKeyRepo {
	mock := &MockEncryptedKeyRepo{ctrl: ctrl}
	mock.recorder = &MockEncryptedKeyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncryptedKeyRepo) EXPECT() *MockEncryptedKeyRepoMockRecorder {
	return m.recorder
}

// GetUserEncryptedKey mocks base method.
func (m *MockEncryptedKeyRepo) GetUserEncryptedKey(arg0 context.Context, arg1 domain.UserID) (domain0.EncryptedKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserEncryptedKey", arg0, arg1)
	ret0, _ := ret[0].(domain0.EncryptedKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserEncryptedKey indicates an expected call of GetUserEncryptedKey.
func (mr *MockEncryptedKeyRepoMockRecorder) GetUserEncryptedKey(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserEncryptedKey", reflect.TypeOf((*MockEncryptedKeyRepo)(nil).GetUserEncryptedKey), arg0, arg1)
}

// SetUserEncryptedKey mocks base method.
func (m *MockEncryptedKeyRepo) SetUserEncryptedKey(arg0 context.Context, arg1 domain.UserID, arg2 domain0.EncryptedKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserEncryptedKey", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserEncryptedKey indicates an expected call of SetUserEncryptedKey.
func (mr *MockEncryptedKeyRepoMockRecorder) SetUserEncryptedKey(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserEncryptedKey", reflect.TypeOf((*MockEncryptedKeyRepo)(nil).SetUserEncryptedKey), arg0, arg1, arg2)
}
