// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	domain "github.com/SergeyRG/secrets-manager/server/internal/files/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFilesRepository is a mock of FilesRepository interface.
type MockFilesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFilesRepositoryMockRecorder
	isgomock struct{}
}

// MockFilesRepositoryMockRecorder is the mock recorder for MockFilesRepository.
type MockFilesRepositoryMockRecorder struct {
	mock *MockFilesRepository
}

// NewMockFilesRepository creates a new mock instance.
func NewMockFilesRepository(ctrl *gomock.Controller) *MockFilesRepository {
	mock := &MockFilesRepository{ctrl: ctrl}
	mock.recorder = &MockFilesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilesRepository) EXPECT() *MockFilesRepositoryMockRecorder {
	return m.recorder
}

// AddFile mocks base method.
func (m *MockFilesRepository) AddFile(arg0 context.Context, arg1 domain.FileID, arg2 io.ReadCloser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFile", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFile indicates an expected call of AddFile.
func (mr *MockFilesRepositoryMockRecorder) AddFile(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFile", reflect.TypeOf((*MockFilesRepository)(nil).AddFile), arg0, arg1, arg2)
}

// GetFile mocks base method.
func (m *MockFilesRepository) GetFile(arg0 context.Context, arg1 domain.FileID) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile", arg0, arg1)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFile indicates an expected call of GetFile.
func (mr *MockFilesRepositoryMockRecorder) GetFile(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockFilesRepository)(nil).GetFile), arg0, arg1)
}

// MockFilesStateRepository is a mock of FilesStateRepository interface.
type MockFilesStateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFilesStateRepositoryMockRecorder
	isgomock struct{}
}

// MockFilesStateRepositoryMockRecorder is the mock recorder for MockFilesStateRepository.
type MockFilesStateRepositoryMockRecorder struct {
	mock *MockFilesStateRepository
}

// NewMockFilesStateRepository creates a new mock instance.
func NewMockFilesStateRepository(ctrl *gomock.Controller) *MockFilesStateRepository {
	mock := &MockFilesStateRepository{ctrl: ctrl}
	mock.recorder = &MockFilesStateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilesStateRepository) EXPECT() *MockFilesStateRepositoryMockRecorder {
	return m.recorder
}

// AddFileState mocks base method.
func (m *MockFilesStateRepository) AddFileState(arg0 context.Context, arg1 domain.FileID, arg2 domain.FileState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFileState", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFileState indicates an expected call of AddFileState.
func (mr *MockFilesStateRepositoryMockRecorder) AddFileState(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFileState", reflect.TypeOf((*MockFilesStateRepository)(nil).AddFileState), arg0, arg1, arg2)
}

// GetFileState mocks base method.
func (m *MockFilesStateRepository) GetFileState(arg0 context.Context, arg1 domain.FileID) (domain.FileState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileState", arg0, arg1)
	ret0, _ := ret[0].(domain.FileState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileState indicates an expected call of GetFileState.
func (mr *MockFilesStateRepositoryMockRecorder) GetFileState(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileState", reflect.TypeOf((*MockFilesStateRepository)(nil).GetFileState), arg0, arg1)
}
